export const SITE = {
  name: 'Shubham Hi-Tech Hospital and Test Tube Baby Centre',
  shortName: 'Shubham Hospitals',
  tagline: 'Hi-Tech Treatment, At Truly Affordable Cost!',
  url: 'https://shubham-hospitals.com',
  phone: '+91-8668954915',
  phoneHref: 'tel:+918668954915',
  whatsapp: 'https://wa.me/918668954915',
  email: 'shubhamhospital111@gmail.com',
  address: 'Badnera Rd, opp. Mantri Motors, Deorankar Nagar, Amravati, Maharashtra 444605',
  facebook: 'https://www.facebook.com/shubhamhitechhospital',
  instagram: 'https://www.instagram.com/shubham_hitech_hospital',
  google: 'https://share.google/xMmIQwSGrP6VOKThO',
  youtubeHospital: 'https://youtube.com/@shubhamhitechhospital',
  youtubeDrManan: 'https://youtube.com/@drmananboob.gynendoscopy',
  directions: 'https://www.google.com/maps/dir/?api=1&destination=Shubham+Hi-Tech+Hospital+and+Test+Tube+Baby+Centre,+Badnera+Rd,+Amravati,+Maharashtra+444605',
  heroImage: '/images/hero-hospital.webp',
  mapsEmbed: 'https://maps.google.com/maps?q=Shubham%20Hi-Tech%20Hospital%20%7C%20Best%20Infertility%20and%20Laparoscopy%20Centre%20in%20Amravati%2C%20Badnera%20Rd%2C%20opp.%20Mantri%20Motors%2C%20Deorankar%20Nagar%2C%20Amravati%2C%20Maharashtra%20444605&t=m&z=14&output=embed&iwloc=near',
  logoHeader: '/images/logo.png',
  logoWhite: 'https://shubham-hospitals.com/wp-content/uploads/2026/06/Shubham-White-Logo.png',
  favicon: 'https://shubham-hospitals.com/wp-content/uploads/2025/09/cropped-Shubham-Hospital-Favicon-New-270x270.png',
  ogImage: 'https://shubham-hospitals.com/wp-content/uploads/2026/06/Shubham-Final-Logo-scaled.png',
};

export const CLINIC_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'MedicalClinic',
  name: SITE.name,
  alternateName: 'Shubham Hospitals',
  url: SITE.url,
  logo: SITE.ogImage,
  image: SITE.ogImage,
  telephone: '+918668954915',
  email: SITE.email,
  slogan: SITE.tagline,
  foundingDate: '1995',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'Badnera Rd, opp. Mantri Motors, Deorankar Nagar',
    addressLocality: 'Amravati',
    addressRegion: 'Maharashtra',
    postalCode: '444605',
    addressCountry: 'IN',
  },
  medicalSpecialty: ['Gynecologic', 'Obstetric', 'Surgical'],
  openingHoursSpecification: [
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      opens: '11:00',
      closes: '17:00',
    },
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      opens: '19:00',
      closes: '21:30',
    },
  ],
  sameAs: [SITE.facebook, SITE.instagram],
};
